# This rule is not used by the project example-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over example.kubebuilder.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: example-operator
    app.kubernetes.io/managed-by: kustomize
  name: example-admin-role
rules:
- apiGroups:
  - example.kubebuilder.io
  resources:
  - examples
  verbs:
  - '*'
- apiGroups:
  - example.kubebuilder.io
  resources:
  - examples/status
  verbs:
  - get
